# Locomotion

## Workflow

1. Choose whether to code child or mom locomotion first
2. Code each pass according to definitions in Datavyu Locomotion Codes
3. Run Ruby script to check for typos

## Child locomotion pass

### Datavyu locomotion codes for child {-}

There are 3 columns associated with child locomotion codes: id for child locomotion, child locomotion column, and a comments column for the child locomotion coding.

#### Child locomotion id Column {-}

**Column name**: `obj_id_child`</br>
**Code**: (\<lab_id\>, \<childloc_coder\>, \<childloc_date\>, \<childloc_mins\>,  \<relchildloc_coder\>, \<relchildloc_date\>)

Code the loc_id_child column according to the definitions for coding the id column.

#### Child locomotion Column {-}

Column name: `childloc`</br>
Code: (\<loc_lfmdr\>)</br>

##### General Orientation {-}

This code captures the times that the child is engaged in salient self-generated locomotion in any form (i.e., bum shuffling, scooting, belly crawling, hands-knees crawling, cruising, supported walking, independent walking, etc.). Also included in this pass are the times when the child is riding a locomotor device, the child is being held by mom or mom is restricting locomotion, the times child is constrained in child furniture (e.g., a belted chair, highchair, or stroller) OR when locomotion cannot be reliably coded (coded as missing in this pass). Coders do not score instances when the child is stationary but could have locomoted. Bouts of locomotion are scored as events, where the gray spaces between cells mean the child is stationary but not held and not constrained.
Coders are watching/tagging the duration of each of these events (locomotion, falls, mom-constrained, device-constrained, riding a toy with wheels, not visible) by marking onset/offset times. To determine locomotion, coders are watching for steps with the feet, the knees, or movements with the bum. Any other movements that are not initiated from these three body locations are considered to be a transition between postures and are counted as stationary, because it is likely a transition rather than salient locomotion.
 
##### Value list {- #child_locomotion_values}

[‘l’ = locomotion](#child_locomotion)</br>
[‘f’ = fall](#child_fall)</br>
[‘m’ = mom constrained](#mom_constrained). Mother is constraining child locomotion by holding or carrying.</br>
[‘d’ = device constrained](#device_constrained). Child’s locomotion is restricted by a device (highchair, stroller, changing table, bathtub, car seat, etc.)</br>
[‘r’ = riding a locomotive device (bike, scooter, car, etc.)](#ride)</br>
[‘.’ = when the child is off camera or the child's feet/knees/bum are off camera and the coder cannot see or infer whether the child is locomoting.](#child_missing)</br>

##### Operational Definitions {-}

###### Locomotion (l) {#child_locomotion}

Code ‘l’ when the child is engaged in self-generated locomotion in any form (i.e. bum shuffling, scooting, belly crawling, hands-knees crawling, hands-feet crawling, cruising, supported walking, independent walking, marching in place, jumping, hopping, etc.). Locomotion occurs when the entire body is displaced in any direction in space—forward, sideways, backward, in-place— because the child is taking a “step”.  A child takes a “step” by shifting weight from one foot/knee onto the other (i.e., weight must be shifting onto a swinging foot/knee in the air to count as moving; if not, this is stationary).
This code counts locomotion regardless of whether the child maintains balance independently or the child's balance is supported by a parent or external object/apparatus. This code also counts even if the child is taking uncontrolled steps while losing balance (i.e. stumbling steps before a fall). Any self-generated locomotion where the child is using a toy, baby walker, furniture, etc. for support and pushing or moving the object, counts as locomotion. (NOTE: If the child is on top and riding a toy with wheels, this does not count as locomotion. See rules for riding). 

If the child is upright:

If the child is upright on both feet without support, every step counts.
NOTE: Do not include pivots. Be careful of bouts that start or end with “pivots” – part of the child's foot is moving but the entire foot is not displaced (e.g. toes move in air but heel rotates on floor, heel moves in air while toes rotate on floor). If a bout starts or ends with one of these pivots, do not include pivot movements as part of the locomotion bout. 
 
If child is upright but using a surface for support:
If a child is upright on both feet while supported by furniture, toy, or mom, the duration of each step has to be less than or equal to 1 second in duration. If the child is using hands for support while swinging one leg for more than 1 second, do not code as locomotion. We want to exclude time when the child is not locomoting but one foot is in the air for an extended period of time (> 1s).

If child is NOT upright:
If the child is NOT upright on both feet (e.g., crawling on belly, hands knees crawling, bum shuffling, etc.) then a bout has to include 3 or more consecutive steps with foot, knee, or bum to count as locomotion. Do not try to code one bum shuffle (child scoots bum back once while sitting on the floor) or one crawl step (moves the knee one time when on the floor). Most likely that is just a shift of position or the beginning of a transition (which is not coded. See rules for transitions). Do not count turning of the body if the bum does not displace (turning with their hands/feet). 

NOTE for hands/feet crawling:

For hands/feet crawling, both hands need to be on the floor. So if the first or last step only has one hand on the floor, consider this a transition.
Crawling can be a mix between knee and foot crawling. Code onset based on which body part begins the movement (foot or knee)

NOTE for belly crawling or bum shuffling:

Only code locomotion if the child makes at least 3 reliable belly-crawling movements (RARE).
 
Do not include any transitions

Do not include any transition to another posture (e.g., sit to upright/walk, sit to crawl, crawl to upright, etc). The first walking/crawling step will be when the foot/knee moves forward in any direction. The final step in the bout has to be a real walking/crawling step (i.e., it is not the last half step or little attempt-step that looks like a transition into the sit). For example, if the child transitions from sitting to crawling; the first step is after the transition ends and the last step is just before another transition begins.
Do not include any time a child is rolling (either on furniture or floor). This is not a reliable source of locomotion and is often part of a transition.
 
NOTE for climbing onto/down from furniture:

Getting down from furniture: If the child bum shuffles or slides to get off of furniture, consider this a transition and therefore do not code until both of the child’s feet have landed on the floor.

Climbing onto furniture:

If the child is locomoting and climbs onto furniture without stopping, code this entire bout as locomoting.
If the child is locomoting on the floor and stops for more than 1 s before climbing onto the furniture (e.g. child walks up to the couch, lifts one leg and stops for more than 1s) then set the offset of the locomotion bout when child stops. After the child climbs onto the furniture, the child could transition to stationary (don’t code this as locomotion) OR start a new bout of locomotion (remember only code crawling if 3 or more steps).
 
NOTE for locomoting up/down stairs:
If the child is going up/down stairs in any manner (walking, crawling, belly-crawling, bum shuffling), count all possible locomotion using regular locomotion codes. Stairs are different from climbing onto/down from the furniture note above.
 
###### Setting the Onset & Offset of a locomotion bout: {-}

Onset of an upright “locomotion bout” is the first frame when the whole foot is displaced (i.e when the foot lifted off the ground). The foot doesn't necessarily have to come off the ground, but the foot has to slide forward, backward or sideways. The onset for a non-upright “locomotion bout” is the first frame when the knee/foot or bum is displaced in space.
Offset is the frame when the child takes the last step before a 1s pause.

##### Falls (f) {- #child_fall}

Code 'f' if the child loses control over his/her body (i.e., balance) and cannot recover on his/her own before his/her body hits the ground. If the child loses balance, but catches him/herself before the above body parts hit the ground, do not count as a fall.
All falls count. They can happen while upright, on/off furniture or other elevation, while sitting, or while engaged in locomotion (walking or crawling). Falls can happen while the mom is holding the child's hand or while the child is holding onto furniture or another support.
A loss of balance must occur before any of the body parts hit the ground. Sometimes babies will actively choose to drop to the floor (e.g., jumping and dropping, flopping down from a couch to the floor, plopping down into a sit, where they let themselves fall down into a sitting position). These instances should NOT count as a fall.
Parent-involved falls should only be coded as a fall if the parent catches the child after the child loses balance, effectively supporting the child's entire weight. In this scenario, the child would have fallen if not for parent rescue (i.e., the body part would have hit the ground). Parents must catch after the child has begun to lose balance.
Falling can occur immediately after mom-constrained if mom and child fell together. Falling can occur immediately after device-constrained if device tips over or the mechanism of constraint fails. Falling can occur immediately after riding if falls off of the riding device.
 
###### Setting the Onset & Offset for falls: {-}

Falls can be coded as separate events (child is standing stationary and then falls) or immediately following another code (child is locomoting and then falls). There should only be 1ms between the previous code and the onset of the falling event if the fall ends the previous code (continuous coding).

Onset is the first frame when the child begins to lose balance.

Offset when the child's body (as defined below) hits the floor.

From an upright or squatting position: a loss of balance results in the hands, knees, or a toy in the hands hitting the ground; child's bum hitting the ground; or head hitting the ground.
From a crawling position: a loss of balance results in the face, head, chest, or side of the torso hitting the ground.
From a sitting position: a loss of balance results in the head, chest, side of torso, or back hitting the ground.

##### Mom-constrained (m) {- #mom_constrained}

Code 'm' when the child is being constrained and supported by the mother. During a mother constraint, the mother can be moving (carrying) or stationary (holding). Code 'm' when any of the following scenarios occur:
Child feet in the air: Both feet are in the air because of mom lifting up the child, child sitting on mom’s lap while the mom is sitting on furniture, child is on a surface with mom constraining the movement of the child with her hands. Exception: If child and mom are playing a “bouncing/jumping” game, where the feet are leaving the surface of support repeatedly, code as ‘m’. If the child takes steps while supported then this should be coded ‘l’.
Mom is holding child: If child is sitting on mom’s lap, or child is breastfeeding, code as ‘m’
Mom is acting as the base of support: Child’s surface of support is mom, legs can be in the air or not. Child is lying, sitting, standing, climbing, stepping, or crawling on mom’s body (most likely on the mom’s lap). 
Note: Child sitting on the floor between the mom’s legs or on the couch next to mom, even if the mom is touching the child would not be coded as ‘m’, this is considered stationary.
Mom constrains the child while on an elevated surface. The child’s feet are not in the air but the mom is restricting the movements, possibly for safety, while the child is on an elevated surface (e.g., mom holding child while sitting on the kitchen counter, mom holding child at the trunk while going down a slide). Note: If the child is sitting directly on a piece of furniture with legs dangling but mom is not constraining or supporting the child in any way, and the child could stand and locomote on their own, do not code as ‘m’. This would be considered stationary. If the child is in a device code as ‘d’.
NOTE: if the child is crawling or walking on a surface but the mom is providing support (e.g., holding the child’s hands or waist) code this as ‘l’, because this is considered supported locomotion.

###### Setting the Onset & Offset of mom-constrained: {-}

Onset of “mom-constrained” is the first frame when mom lifts up the child's whole body off the current surface and up into the air in mom's arms (as defined below).

From an upright or squatting position: when a child's second foot leaves the surface.
From lying down on back: when bum leaves the surface of support.
From lying on tummy: when tummy leaves the surface of support.
From a crawling position: second knee/foot leaves the surface of support.
From a sitting position: when bum leaves the surface of support.
Offset of “mom-constrained” is when mom places the child down and the child starts supporting his own weight in any posture (as defined below).

Mom places the child in an upright position: when both feet touch the ground.
Mom places the child lying down on the back: when bum touches the surface. This is usually the case when mom puts the child on the changing table.
Mom places the child lying down on tummy: when tummy touches the surface.
Mom places the child in a crawling or kneeling position: when both knees touch the ground.
Mom places the child in a sitting position: when the child's bum touches the surface of support. This can be a chair, highchair, furniture, floor.
 NOTE for when transitioning from “mom-constrained” to “device-constraint” to “mom-constrained” (‘m’, ‘d’, ‘m’):

“Mom held” and “device-constraint” are likely to be continuous. Mom-constraint ends as she puts the child into a device. Mom takes the child out of the device is device-constraint transitioning into mom-constraint.
These should be continuous coding with 1ms between each code. Do not wait until the child is fully strapped and buckled on the device (See onset codes above). 
NOTE for when transitioning from “locomotion” to “mom-constrained” to “locomotion” (‘l’, ‘m’, ‘l’):

In cases of “locomotion” followed by “mom-constrained”

Offset for ‘l’ should be the last real step before mom lifts the child off the surface. Codes for ‘l’ and ‘m’ can be continuous but not always are.
In cases of “mom-constrained” followed by “locomotion”

If the child immediately starts locomoting when mom is putting the child back down, the onset for ‘l’ is when the second foot, hand, or knee touches the floor.
In cases of “missing” followed by “mom-constrained”

If the child is being held by mom and taken outside of the camera's view (missing, around the corner, etc.), continue coding for mom-constrained if the child is still constrained when back in view.

##### Device (d) {- #device_constrained}

Code ‘d’ if the child is constrained (could be strapped or not) in a device that restricts locomotion (e.g., a highchair, stroller, car seat, etc.). The device could restrict locomotion by binding the child from the front or sides (bumbo seat), lifting them off the ground (high chair, changing table), constraining their freedom to move upright (car seat, stroller), or strapped in. Devices can never be household furniture (e.g. couch, chair, or bed) not intended for children. Child-designed furniture (e.g. wooden or plastic child chair) is not a device unless the child is strapped into it and locomotion is restricted.
NOTE: Child walker is NOT a device. This would count as supported walking because that’s the whole point of a child walker. Jolly jumpers and exersaucers count as a device even though the child is moving or jumping around because this restricts locomotion.
For devices that always restricts locomotion (with or without straps): if the device restricts locomotion regardless of whether the child is strapped in or not (e.g. highchair with bounded sides, tall stroller, bumbo seat) code as ‘d’ when child is on the device, not when straps are buckled.

For child-designed furniture that restricts locomotion only when child is strapped in: If child-designed furniture only restricts locomotion because the child is strapped in (e.g. child chair that the child could get on/off independently) then code as ‘d’ when and only when the child is strapped in. Onset is when the first strap is buckled and offset is when the last strap is unbuckled. Do not code the time when the child is stationary and free to initiate locomotion from the piece of furniture.

For ride toys that restrict locomotion when the child is strapped in: If a ride toy only restricts locomotion because the child is strapped in (e.g. a toy like stroller), then code as ‘d’ when and only when the child is strapped in.

For changing tables: If mom places the child on a changing table (off the ground), code as ‘d’ as long as the child is on the changing table. Only code mom-restrained when mom picks up child from floor and puts on the changing table, and when mom picks up child from changing table and puts him/her back on the floor. Do not code ‘d’ when mom is changing the child on a changing mat on the floor (follow rules for mom-restrained if mom picks child up or locomotion rules if child starts crawling or walking).

 NOTE for when transitioning from “mom-constrained” to “device-constraint” to “mom-constrained” (‘m’, ‘d’, ‘m’): “Mom held” and “device-constraint” are likely to be continuous. Mom-constraint ends as she puts the child into a device. Mom takes the child out of the device is device-constraint transitioning into mom-constraint.

These should be continuous coding with 1ms between each code. Do not wait until the child is fully strapped and buckled on the device unless the straps are the only method of restricting locomotion, then treat the unbuckled part as stationary.
 Setting the Onset & Offset for device:

Onset of device constrained is when the child's butt first touches the restrictive device. Do not wait until the child is strapped to the device.
Offset of constrained is when the butt leaves the device as the parent starts to take the child out (usually by lifting them out). (See also mom-constrained section)..
 
##### Ride (r) {- #ride}

Code ‘r’ if the child is riding a locomotive toy (e.g. child car, bike, scooter, doll stroller, etc.) with wheels. The child can be sitting (bum on the seat), kneeling with one knee, standing (on a scooter), straddling on a bicycle or tricycle with both legs on opposite sides of a central support riding toy. The device does not necessarily need to be in motion for you to code this as ‘r’. If a riding toy does not have wheels then it does not count as ‘r’ and should be considered stationary (e.g. if a child is sitting on a rocking horse).

Do not code as ‘r’ if the child's bum, knee, or feet is not on the riding device. Taking steps while pushing a riding toy while not straddling, sitting, or kneeling on it or while walking around the toy count as locomotion.  If steps occur as the child is moving onto/off of the device, follow codes for ‘l’ (remember not to code transitions).
 
###### Setting the Onset & Offset for ride: {-}

Onset of ride is when the child's bum or knee first touches the riding toy (if sitting in a bike or car) or the second foot is off the ground (if standing on a scooter). Straddling begins when both feet are on the ground.
Offset of ride is when the child's bum, knee, or both feet leave the riding toy.

##### Missing (.) {- #child_missing}

Code ‘.’ if the child is not fully visible and you cannot reliably code ‘l’, ‘d’, ‘m’, or ‘r’. Child could be completely out of view or their lower body could be occluded and it is not clear based on the movement of the top half of the body if the child is locomoting. A missing bout must last for at least 1 second.
 
If child is missing for less than 1s:

If missing time less than 1s occurs between 2 identical codes (e.g. ‘l’ and ‘l’) do not split bout; instead, continue locomotion bout from original cell until end of that locomotion bout.
If missing time (< 1s) occurs between 2 non-identical codes, (e.g. ‘l’ before missing, stationary after missing), code offset of the locomotion cell as the first frame where you cannot see the child.
 
If child is missing for more than 1s:
Code CONTINUOUSLY so that the ‘.’ fills all of the time in the spreadsheet between the two events that are visible. For example, if the child is locomoting, then feet aren’t visible, and then reappears constrained in a car seat, there should only be 1ms between the cells (press the ‘0’ key on the numpad to do this automatically).

Going around corners:

This should be coded according to the above rules. After the child is fully out of view (and this lasts for at least 1s), code as missing. Begin coding locomotion again when the child is back in view. This is a continuous code (see above for when missing (> 1s) captures all time between two cells).
If child’s lower body is occluded (by furniture, mom, toys) or is outside of camera view:

Code as ‘.’ if you cannot see both knees or both feet to determine the onset and offset of locomotion (e.g. when a child is locomoting behind furniture, but you cannot tell when they started taking a step). If this occurs BUT you can determine the onset and offset from a clear view of their ankle/foot, code as locomotion as normal. Do not make judgment calls if you cannot clearly determine the onset and offset even if the child is visibly locomoting. NOTE: it still has to follow the 1-second rule of occlusion

Setting the Onset & Offset for missing \<.\>:

Onset of missing is the first frame when the child’s locomotion cannot be reliably coded (see above rules for specific instances).
Offset of missing is the first frame when the child's locomotion status can reliably be coded (see above rules for specific instances).

### How to Code the Child Locomotion Column {-}

- Set “JUMP-BACK-BY” key to 1 s.
- Enable cell highlighting (cmd + shift +F). Enable temporal mode (cmd T).
- Watch in real time for the child's movement.
- Watch the child's feet and knees.
- As soon as you see child's foot/knee lift up off of the ground; hit #5-STOP and then hit “JUMP-BACK-BY” to go back to the timestamp that is just before the lift. Then JOG forward by hitting #3-JOGFORWARD until you reach the Onset of that cell. If you go too far, you can JOG backward by hitting #1-JOGBACK. You will likely have to hit the JOG keys numerous times. If you feel that you have either jumped too far back or went too far forward, hold the JOG keys to move in either direction a bit faster. Hit ENTER to create a new cell at this Onset.
- Now, watch in real time to see when the child stops moving. The Offset is when the child stops moving for at least 0.5 s (the pause has to look and feel like an actual pause when you are watching in real time; don't simply end a bout of locomotion because there was a1s pause, especially if it looks like the child is about to take another step). The first frame when the foot/knee stops moving or when the foot settles into its final position (sometimes infants stop their walking bout on their tip-toes) is the offset. The same applies to sliding steps.
- To set the Offset, use the same rules for mechanics as with the onset. Hit #5-STOP and then hit “JUMP-BACK-BY” to go back to the timestamp that is just before the lift. Then JOG forward by hitting #3-JOGFORWARD until you reach the Offset of that cell. If you go to far, you can JOG backward by hitting #1-JOGBACK. You will likely have to hit the JOG keys numerous times. If you feel that you have either jumped too far back or went too far forward, hold the JOG buttons to move in either direction a bit faster.

### Check the final coded pass {-}

When finished coding, run the script to check for typos in the child locomotion column. The script will flag any occurrence of typos that arise from an error in setting the onset or offset (not coded, cell with no duration, overlapping cells), consecutive ‘l’ cells that are less than 1s apart (and should be merged), and any invalid codes (any characters besides ‘l’, ‘f’, ‘m’, ‘d’, ‘r’, or ‘.’). Fix errors and run the script again. When all the errors have been resolved the script will inform that no errors are found.

## Mom locomotion pass

### Datavyu Locomotion Codes for Mom {-}

There are 3 columns associated with mom locomotion codes: id for mom locomotion, mom locomotion column, and comments column for the mom locomotion coding.

#### Mom locomotion id Column {-}

**Column name**: `obj_id_mom`</br>
**Code**: (\<lab_id\>, \<momloc_coder\>, \<momloc_date\>, \<momloc_mins\>,  \<relmomloc_coder\>, \<relmomloc_date\>)

Code the loc_id_mom column according to the definitions for coding the id column.

#### Mom locomotion Column {-}

**Column name**: `momloc`</br>
**Code**: (\<loc_lf\>)

##### General Orientation {-}

This code captures the times that mom is engaged in locomotion or falls. Bouts of locomotion are scored as events, where the gray spaces between cells mean the mom is stationary. Coders are watching/tagging each of these events by marking onset/offset times for the duration of locomotion bouts. Coders are watching for steps with the feet, the knees, or the bum.  Any other movements that are not initiated from these three body locations is considered to be a transition between postures and is subsumed by stationary, as it is not locomotion. Bouts that are coded as ‘.’ means that mom is off camera or her legs are off camera, and the coder cannot see or infer whether mom is stationary or moving.

##### Value list {-}

[‘l’ = locomotion](#mom_locomotion)
[‘f’ = fall](#mom_fall)
[‘.’ = when mom is off camera or the mom's feet/knees/bum are off camera and the coder cannot see or infer whether the mom is locomoting at any point during this period of missing](#mom-missing).
[‘x’ = when mom's feet/knees/bum are off camera, coder cannot set a reliable onset and offset, but coder can infer that mom is locomoting at some point of this period of missing.](#mom_undetermined)

##### Operational Definitions {-}

###### Locomotion (l) {- #mom_locomotion}

Code ‘l’ when the mom is engaged in locomotion of any form (i.e., walking, scooting, knee-walking, crawling).
If you’re not sure whether the mom is moving or stationary (e.g., occlusion behind furniture or unclear video footage), then this is missing data and the offset of the locomotion bout should be set to the last frame where you can see mom.
The subsequent cell (where you cannot see anything or make an inference about movement) should be coded as “.” until you can see mom again.
However, if you can infer that mom is moving or stationary (i.e., head is bobbing, shadow of the leg moving is visible, etc.) then include it in the same bout of locomotion, following the rules for pauses above.
 
Do not include any transitions
Do not include any movement with foot/knee as part of a transition to another posture. For example, if the mom transitions from sitting on the floor to standing, the onset of the locomotor bout would be the first step once she is walking.
Do not include mom holding or swinging one foot in the air
If mom is upright on both feet—regardless of if they are using their hands for support on furniture, toy, and so on—the duration of each step has to be less than or equal to 1 second in duration. That is, in any position, if the mom is standing with one foot in the air for more than 1 second, do not code as locomotion. Set the offset of the locomotor bout when the last foot (i.e. the mom’s standing leg) made contact with the floor. We want to exclude time when the mom is not locomoting but one foot is in the air for an extended period of time (> 1s)—even if she eventually lowers than foot.

Setting the Onset & Offset of a locomotion bout:

Onset is the first frame when the whole foot is displaced (i.e when the foot lifted off the ground). The foot doesn't necessarily have to come off the ground, but the foot has to slide forward, backward or sideways.
Offset is the frame when the mom takes the last step before a 1s pause.
 
###### Falls (f) {- #mom_fall}

Code 'f' if the mom loses control of her body (i.e., balance) and cannot recover on her own before the body (bum, hands, torso) hits the ground. All falls count. They can happen while upright, on/off furniture or other elevation, while sitting, or while engaged in locomotion.
From an upright or squatting position: a loss of balance results in the hands, knees, or a toy in the hands hitting the ground.

Onset & Offset for ‘f’ {-}

Onset is the first frame when mom begins to lose balance.

Offset when mom's body hits the floor. Usually the hands to arrest fall.

###### Missing (.) {- #mom_missing}

Code ‘.’ if mom’s lower body is occluded such that you cannot see at least the knees or below, you cannot reliably code ‘l’, or ‘f’. Mom’s locomotion can be coded from the feet, ankles, shins, or knees—but not from the thighs, hips, upper body, or head alone. DO NOT infer movement if you cannot at least see the feet, ankles, shins, or knees, even if you can clearly tell that mom is locomoting. Onsets/offsets may not be reliable and small steps will be hard to see. The goal is to make coding easy and reliable with a hard rule, rather than having to guess. (Other labs can always go back and code mom locomotion during the occluded periods.)

Stationary and seated

If mom is stationary and seated (e.g., on the floor, couch, chair), and as long as you can see any part of her trunk or lower body to determine she has not locomoted do not code as ‘.’ (see rules below). If mom is stationary and out of view for less than 30 seconds, and does not move from the same location, do not code as ‘.’. If mom is stationary and out of view, and when she is visible again, she has moved from the previous location code as ‘.’ on the first frame when she was out of view (i.e., rewind back to time when she went out of view for the first time, before she locomoted). 

If mom is out of view less than 1s: If missing time less than 1s occurs between 2 identical codes (e.g. ‘l’ and ‘l’) do not split bout; instead, continue locomotion bout from original cell until end of that locomotion bout.
If missing time (< 1s) occurs between 2 non-identical codes, (e.g. ‘l’ before missing, stationary after missing), code offset of the locomotion cell as the first frame where you cannot see the mom.

If mom is out of view for more than 1s: Code CONTINUOUSLY so that the ‘.’ fills all of the time in the spreadsheet between the two events that are visible. For example, if the mom is locomoting, then feet aren’t visible, and then reappears locomoting, there should only be 1ms between the cells (press the ‘0’ key on the numpad to do this automatically).
If mom is going around corners:

This should be coded according to the above rules. After mom is fully out of view (and this lasts for at least 1s), code as missing. Begin coding locomotion again when mom is back in view. This is a continuous code (see above for when missing (> 1s) captures all time between two cells).
If mom’s lower body is occluded (by furniture, child, toys) or is outside of camera view:

Code as ‘.’ if you cannot see at least the ball of foot or heel of both feet (it doesn’t need to be the same part on both feet). NOTE: it still has to follow the 1-second rule of occlusion.
If mom is out of view

Setting the Onset & Offset for missing \<.\>:

Code onset and offset depending on the relevant body part in view for the type of posture:

Locomotor postures:

Walking = feet</br>
Knee walking = knees</br>
Bum shuffling = bum</br>
Hands-knees crawling = knees</br>
Cruising = feet</br>
Jumping = feet</br>

Sedentary postures:

Sitting = bum or feet</br>
Standing = feet</br>
Quadruped = knees</br>

Onset & Offset for ‘.’

Onset of missing is the first frame where mom’s locomotion cannot be reliably coded (see above rules for specific instances).

Offset of missing is the first frame where mom’s locomotion status can reliably be coded (see above rules for specific instances).

###### Undetermined (x) {- #mom_undetermined}

Code ‘x’ if mom is not fully visible and you cannot reliably code ‘l’, or ‘f’, but you can tell that mom is in motion. It is clear based on the movement of the top half of the body that mom is locomoting but it is impossible to code the exact onset and offset of the locomotor bout. An ‘x’ bout must last for at least 1 second.
Do not make judgment calls if you cannot clearly determine the onset and offset even if the mom is visibly locomoting. Code instead as ‘x’.
The goal of this code is that it uses the exact same criteria for onset and offset of missing, but allows the coder to indicate that at some point during this missing, the mom clearly locomoted.

### How to Code the Mom Locomotion Column {-}

- Set “JUMP-BACK-BY” key to 1 s.
- Enable cell highlighting on the controller (cmd + shift +F). Enable temporal mode (cmd T).
- Watch in real time for the mom's feet and knees movement.
- As soon as you see mom's foot/knee lift up off of the ground; hit #5-STOP and then hit “JUMP-BACK-BY” to go back to the timestamp that is just before the lift. Then JOG forward by hitting #3-JOGFORWARD until you reach the onset of that cell. If you go too far, you can JOG backward by hitting #1-JOGBACK. If you feel that you have either jumped too far back or went too far forward, hold the JOG keys to move in either direction a bit faster. Hit ENTER to create a new cell at this Onset.
- Now, watch in real time to see when the mom stops moving. The Offset is when the mom stops moving for at least 0.5 s (the pause has to look and feel like an actual pause when you are watching in real time; don't simply end a bout of locomotion because there was a 0.5-s pause, especially if it looks like the mom is about to take another step). The first frame when the foot/knee stops moving or when the foot settles into its final position is the offset. The same applies to sliding steps.
- To set the Offset, use the same rules for mechanics as with the Onset. Hit #5-STOP and then hit “JUMP-BACK-BY” to go back to the timestamp that is just before the lift. Then JOG forward by hitting #3-JOGFORWARD until you reach the Offset of that cell. If you go too far, you can JOG backward by hitting #1-JOGBACK. You will likely have to hit the JOG keys numerous times. If you feel that you have either jumped too far back or went too far forward, hold the JOG keys to move in either direction a bit faster.

### Check the final Mom Locomotion Coded Pass {-}

When finished coding, run the script to check for typos in the mom locomotion column. The script will flag any occurrence of typos that arise from an error in setting the onset or offset (not coded, cell with no duration, overlapping cells), consecutive ‘l’ cells that are less than 1s apart (and should be merged), and any invalid codes (any characters besides ‘l’, ‘f’, ‘.’ or ‘x’). Fix errors and run the script again. When all the errors have been resolved the script will inform that no errors are found.